name: Deploy to IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Verify .NET
        run: dotnet --info

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release

      - name: Publish
        run: dotnet publish -c Release -o publish

      - name: Deploy to IIS
        shell: powershell
        run: |
             - name: Deploy Files
               shell: powershell
              run: |
                    robocopy publish C:\inetpub\wwwroot\frontend /E /R:1 /W:1
                    exit 0
   
